library(titanic)
data("titanic_train")
head(titanic_train)
titanic_train$Sex = as.factor(titanic_train$Sex)
titanic_train$Survived = as.factor(titanic_train$Survived)
summary(titanic_train)
dropnull_titanic <- na.omit(titanic_train)
survivedList = dropnull_titanic[dropnull_titanic$Survived == 1 , ]
notSurvivedList = dropnull_titanic[dropnull_titanic$Survived == 0, ]
mytable <- table(titanic_train$Survived)
print(table)
lbls <- paste(names(mytable), "\n", mytable, sep = "")
pie(mytable, labels = lbls, main = "Pie chart of Survival Distribution")
hist(titanic_train$Age, xlab = "Age", ylab = "Frequency", main = "Histogram of Age")
barplot(table(notSurvivedList$Sex), xlab = "Gender", ylab = "Frequency", main = "Barplot of Non-Survivors by Gender")
temp <- density(survivedList$Fare, na.rm = TRUE)
plot(temp, type = "n", main = "Fare Charged to Survivors")
polygon(temp, col = "lightgray", border = "gray")
boxplot(titanic_train$Fare, main = "Boxplot of Fare")
